Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,19 +1,25 @@
 #!/bin/sh
 # based on https://github.com/miyagawa/heroku-buildpack-perl/
 
+# Fail fast and fail hard.
+set -eo pipefail
+
 indent() {
   sed -u 's/^/       /'
 }
 
-set -e
-
 BUILD_DIR=$1
 CACHE_DIR=$2
+ENV_DIR=$3
 
 PATH="$BUILD_DIR/local/bin:$PATH"
 
 export PERL5LIB="$BUILD_DIR/local/lib/perl5"
-export PERL_CPANM_OPT="--quiet --notest -l $BUILD_DIR/local"
+PERL_CPANM_OPT="--quiet --notest -l $BUILD_DIR/local"
+if [ -f $ENV_DIR/PERL_CPANM_OPT ]; then
+  PERL_CPANM_OPT="$PERL_CPANM_OPT $(cat $ENV_DIR/PERL_CPANM_OPT)"
+fi
+export PERL_CPANM_OPT
 
 rm -rf $BUILD_DIR/local
 if [ -d $CACHE_DIR/local ]; then
@@ -27,8 +33,12 @@ if ! [ -e $BUILD_DIR/local/bin/cpanm ]; then
   curl -L --silent https://raw.github.com/miyagawa/cpanminus/master/cpanm | perl - App::cpanminus 2>&1 | indent
 fi
 
+echo "-----> Installing dependencies"
+echo "cpanm options: $PERL_CPANM_OPT" | indent
+cpanm --installdeps . 2>&1 | indent
+
 echo "-----> Installing xls2csv"
-cpanm https://s3.amazonaws.com/staq-buildpack-files/xls2csv-1.07.tar.gz 2>&1 | indent
+cpanm http://search.cpan.org/CPAN/authors/id/K/KE/KEN/xls2csv-1.07.tar.gz 2>&1 | indent
 
 if [ -d $BUILD_DIR/local ]; then
   rm -rf $CACHE_DIR/local
